import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col justify-center bg-gray-200">
        <div className="container flex flex-col items-center justify-center">
          <h1 className="text-lg font-semibold text-gray-700 sm:text-[2rem]">
            Inventario de Vidrios
          </h1>
        </div>
      </main>
    </>
  );
};

export default Home;
