//Next
import { type NextPage } from "next";
import Head from "next/head";

//Material UI
import {
  DataGrid,
  GridToolbar,
  type GridRowsProp,
  type GridColDef,
} from "@mui/x-data-grid";

const rows: GridRowsProp = [
  { id: 1, col1: "Hello", col2: "World" },
  { id: 2, col1: "DataGridPro", col2: "is Awesome" },
  { id: 3, col1: "MUI", col2: "is Amazing" },
];

const columns: GridColDef[] = [
  { field: "col1", headerName: "Column 1", width: 150 },
  { field: "col2", headerName: "Column 2", width: 150 },
];

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col justify-center px-4 py-16">
        <div className="container flex flex-col items-center justify-center gap-12">
          <h1 className="text-lg font-semibold text-gray-700 sm:text-[2rem]">
            Inventario de Vidrios
          </h1>
          <div className="flex flex-col justify-center gap-4">
            <div className="flex w-full justify-end">
              <button className=" rounded-md border border-transparent bg-sky-600 px-4 py-2 text-sm font-medium text-white hover:bg-sky-700">
                Cargar Vidrio
              </button>
            </div>
            <DataGrid
              disableDensitySelector
              rows={rows}
              columns={columns}
              slots={{ toolbar: GridToolbar }}
              slotProps={{
                toolbar: {
                  showQuickFilter: true,
                  quickFilterProps: { debounceMs: 500 },
                },
              }}
              sx={{
                backgroundColor: "white",
                p: 3,
                borderRadius: "0.5rem",
                "& .MuiButtonBase-root": {
                  color: "rgb(2 132 199)",
                },
              }}
            />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
